/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.StoC
{
    public class P072_UnknownMessage : GenericMessage
    {
        public int Unknown0;
        public byte[] Unknown1;
        public byte Unknown2;
        public byte Unknown3;
        public byte Unknown4;
        public int Unknown5;
        public int Unknown6;
        public struct Struct7
        {
            public short Unknown8;
            public short Unknown9;
            public short Unknown10;
            
            public void Serialize(Serializer serializer)
            {
                serializer.Write(this.Unknown8);
                serializer.Write(this.Unknown9);
                serializer.Write(this.Unknown10);
            }
        }
        public Struct7[] Unknown11;
        public float Unknown12;
        public float Unknown13;
        public float Unknown14;
        
        public override ushort Header
        {
            get
            {
                return 72;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.WriteVarint(this.Unknown0);
            for (int i = 0; i < this.Unknown1.Length; i++)
            {
                serializer.Write(this.Unknown1[i]);
            }
            serializer.Write(this.Unknown2);
            serializer.Write(this.Unknown3);
            serializer.Write(this.Unknown4);
            serializer.WriteVarint(this.Unknown5);
            serializer.WriteVarint(this.Unknown6);
            for (int i = 0; i < this.Unknown11.Length; i++)
            {
                this.Unknown11[i].Serialize(serializer);
            }
            serializer.Write(this.Unknown12);
            serializer.Write(this.Unknown13);
            serializer.Write(this.Unknown14);
        }
    }
}
