/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 22-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;
using GameRevision.GW2Emu.Common.Session;

namespace GameRevision.GW2Emu.GameServer.Messages.StoC
{
    public class P154_UnknownMessage : IMessage
    {
        public Vector2[] Unknown0;
        public int Unknown1;
        
        public ushort Header
        {
            get
            {
                return 154;
            }
        }
        
        public ISession Owner {  get;  set; }
        
        public void Serialize(Serializer serializer)
        {
            serializer.Write(Header);
            serializer.Write((byte)Unknown0.Length);
            for (int i = 0; i < Unknown0.Length; i++)
            {
                serializer.Write(Unknown0[i]);
            }
            serializer.WriteVarint(this.Unknown1);
        }
        public void Deserialize(Deserializer deserializer) {}
    }
}
