/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 21-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;

namespace GameRevision.GW2Emu.GameServer.Messages.StoC
{
    public class P288_UnknownMessage : IMessage
    {
        public int Unknown0;
        public int Unknown1;
        public int Unknown2;
        public int[] Unknown3;
        public string Unknown4;
        public string Unknown5;
        public short Unknown6;
        
        public ushort Header
        {
            get
            {
                return 288;
            }
        }
        
        public void Serialize(Serializer serializer)
        {
            serializer.Write(Header);
            serializer.WriteVarint(this.Unknown0);
            serializer.WriteVarint(this.Unknown1);
            serializer.WriteVarint(this.Unknown2);
            serializer.Write((byte)Unknown3.Length);
            for (int i = 0; i < Unknown3.Length; i++)
            {
                serializer.WriteVarint(Unknown3[i]);
            }
            serializer.WriteUtf16String(this.Unknown4);
            serializer.WriteUtf16String(this.Unknown5);
            serializer.Write(this.Unknown6);
        }
        public void Deserialize(Deserializer deserializer) {}
    }
}
