/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.StoC
{
    public class P394_UnknownMessage : GenericMessage
    {
        public byte Unknown0;
        public Vector2[] Unknown1;
        
        public override ushort Header
        {
            get
            {
                return 394;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.Write(this.Unknown0);
            serializer.Write((byte)Unknown1.Length);
            for (int i = 0; i < Unknown1.Length; i++)
            {
                serializer.WriteVector2(Unknown1[i]);
            }
        }
    }
}
