/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.StoC
{
    public class P408_UnknownMessage : GenericMessage
    {
        public int Unknown0;
        public int Unknown1;
        public byte Unknown2;
        public int Unknown3;
        public short[] Unknown4;
        public int Unknown5;
        public int[] Unknown6;
        
        public override ushort Header
        {
            get
            {
                return 408;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.WriteVarint(this.Unknown0);
            serializer.WriteVarint(this.Unknown1);
            serializer.Write(this.Unknown2);
            serializer.WriteVarint(this.Unknown3);
            for (int i = 0; i < this.Unknown4.Length; i++)
            {
                serializer.Write(this.Unknown4[i]);
            }
            serializer.WriteVarint(this.Unknown5);
            serializer.Write((byte)Unknown6.Length);
            for (int i = 0; i < Unknown6.Length; i++)
            {
                serializer.WriteVarint(Unknown6[i]);
            }
        }
    }
}
