/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 21-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;

namespace GameRevision.GW2Emu.GameServer.Messages.StoC
{
    public class P419_UnknownMessage : IMessage
    {
        public int Unknown0;
        public int Unknown1;
        public byte Unknown2;
        public int Unknown3;
        public int Unknown4;
        public byte Unknown5;
        public int Unknown6;
        public int[] Unknown7;
        
        public ushort Header
        {
            get
            {
                return 419;
            }
        }
        
        public void Serialize(Serializer serializer)
        {
            serializer.Write(Header);
            serializer.WriteVarint(this.Unknown0);
            serializer.WriteVarint(this.Unknown1);
            serializer.Write(this.Unknown2);
            serializer.WriteVarint(this.Unknown3);
            serializer.WriteVarint(this.Unknown4);
            serializer.Write(this.Unknown5);
            serializer.WriteVarint(this.Unknown6);
            serializer.Write((byte)Unknown7.Length);
            for (int i = 0; i < Unknown7.Length; i++)
            {
                serializer.WriteVarint(Unknown7[i]);
            }
        }
        public void Deserialize(Deserializer deserializer) {}
    }
}
