/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 24-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Session;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;

namespace GameRevision.GW2Emu.GameServer.Messages.StoC
{
    public class P453_UnknownMessage : GenericMessage
    {
        public int Unknown0;
        public int Unknown1;
        public struct Struct2
        {
            public string Unknown3;
            public int Unknown4;
            public int Unknown5;
            public struct Struct6
            {
                public int Unknown7;
                public byte Unknown8;
                public string Unknown9;
                public Vector2 Unknown10;
                
                public void Serialize(Serializer serializer)
                {
                    serializer.WriteVarint(this.Unknown7);
                    serializer.Write(this.Unknown8);
                    serializer.WriteUtf16String(this.Unknown9);
                    serializer.Write(this.Unknown10);
                }
            }
            public Struct6[] Unknown11;
            
            public void Serialize(Serializer serializer)
            {
                serializer.WriteUtf16String(this.Unknown3);
                serializer.WriteVarint(this.Unknown4);
                serializer.WriteVarint(this.Unknown5);
                serializer.Write((byte)Unknown11.Length);
                for (int i = 0; i < Unknown11.Length; i++)
                {
                    Unknown11[i].Serialize(serializer);
                }
            }
        }
        public Struct2[] Unknown12;
        public short[] Unknown13;
        
        public override ushort Header
        {
            get
            {
                return 453;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            serializer.Write(Header);
            serializer.WriteVarint(this.Unknown0);
            serializer.WriteVarint(this.Unknown1);
            serializer.Write((byte)Unknown12.Length);
            for (int i = 0; i < Unknown12.Length; i++)
            {
                Unknown12[i].Serialize(serializer);
            }
            serializer.Write((byte)Unknown13.Length);
            for (int i = 0; i < Unknown13.Length; i++)
            {
                serializer.Write(Unknown13[i]);
            }
        }
    }
}
