/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.StoC
{
    public class P455_UnknownMessage : GenericMessage
    {
        public struct Struct0
        {
            public int Unknown1;
            public int Unknown2;
            public Vector3 Unknown3;
            public Vector3 Unknown4;
            public byte Unknown5;
            
            public void Serialize(Serializer serializer)
            {
                serializer.WriteVarint(this.Unknown1);
                serializer.WriteVarint(this.Unknown2);
                serializer.WriteVector3(this.Unknown3);
                serializer.WriteVector3(this.Unknown4);
                serializer.Write(this.Unknown5);
            }
        }
        public Struct0[] Unknown6;
        
        public override ushort Header
        {
            get
            {
                return 455;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.Write((byte)Unknown6.Length);
            for (int i = 0; i < Unknown6.Length; i++)
            {
                Unknown6[i].Serialize(serializer);
            }
        }
    }
}
