/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 24-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Session;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;

namespace GameRevision.GW2Emu.GameServer.Messages.StoC
{
    public class P718_UnknownMessage : GenericMessage
    {
        public int Unknown0;
        public int Unknown1;
        public struct Struct2
        {
            public int Unknown3;
            public float Unknown4;
            
            public void Serialize(Serializer serializer)
            {
                serializer.WriteVarint(this.Unknown3);
                serializer.Write(this.Unknown4);
            }
        }
        public Struct2[] Unknown5;
        
        public override ushort Header
        {
            get
            {
                return 718;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            serializer.Write(Header);
            serializer.WriteVarint(this.Unknown0);
            serializer.WriteVarint(this.Unknown1);
            serializer.Write((byte)Unknown5.Length);
            for (int i = 0; i < Unknown5.Length; i++)
            {
                Unknown5[i].Serialize(serializer);
            }
        }
    }
}
