@echo off
echo Starting login server...
start src\GameRevision.GW2Emu.LoginServer\bin\Debug\GameRevision.GW2Emu.LoginServer.exe
echo Starting game server...
start src\GameRevision.GW2Emu.GameServer\bin\Debug\GameRevision.GW2Emu.GameServer.exe