/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 24-07-13
 */

using System;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.GameServer.Messages.CtoS;

namespace GameRevision.GW2Emu.GameServer.Messages
{
    public class ClientMessageFactory : GenericMessageFactory
    {
        protected override IMessage CreateEmptyMessage(ushort header)
        {
            switch (header)
            {
                case 1:
                    return new P001_UnknownMessage();
                case 2:
                    return new P002_UnknownMessage();
                case 3:
                    return new P003_UnknownMessage();
                case 4:
                    return new P004_UnknownMessage();
                case 5:
                    return new P005_UnknownMessage();
                case 6:
                    return new P006_UnknownMessage();
                case 7:
                    return new P007_UnknownMessage();
                case 8:
                    return new P008_UnknownMessage();
                case 9:
                    return new P009_UnknownMessage();
                case 10:
                    return new P010_UnknownMessage();
                case 11:
                    return new P011_UnknownMessage();
                case 12:
                    return new P012_UnknownMessage();
                case 13:
                    return new P013_UnknownMessage();
                case 14:
                    return new P014_UnknownMessage();
                case 15:
                    return new P015_UnknownMessage();
                case 16:
                    return new P016_UnknownMessage();
                case 17:
                    return new P017_UnknownMessage();
                case 18:
                    return new P018_UnknownMessage();
                case 19:
                    return new P019_UnknownMessage();
                case 20:
                    return new P020_UnknownMessage();
                case 21:
                    return new P021_UnknownMessage();
                case 22:
                    return new P022_UnknownMessage();
                case 23:
                    return new P023_UnknownMessage();
                case 24:
                    return new P024_UnknownMessage();
                case 25:
                    return new P025_UnknownMessage();
                case 26:
                    return new P026_UnknownMessage();
                case 28:
                    return new P028_UnknownMessage();
                case 29:
                    return new P029_UnknownMessage();
                case 30:
                    return new P030_UnknownMessage();
                case 31:
                    return new P031_UnknownMessage();
                case 32:
                    return new P032_UnknownMessage();
                case 33:
                    return new P033_UnknownMessage();
                case 34:
                    return new P034_UnknownMessage();
                case 35:
                    return new P035_UnknownMessage();
                case 36:
                    return new P036_UnknownMessage();
                case 37:
                    return new P037_UnknownMessage();
                case 38:
                    return new P038_UnknownMessage();
                case 39:
                    return new P039_UnknownMessage();
                case 40:
                    return new P040_UnknownMessage();
                case 41:
                    return new P041_UnknownMessage();
                case 42:
                    return new P042_UnknownMessage();
                case 43:
                    return new P043_UnknownMessage();
                case 44:
                    return new P044_UnknownMessage();
                case 45:
                    return new P045_UnknownMessage();
                case 46:
                    return new P046_UnknownMessage();
                case 47:
                    return new P047_UnknownMessage();
                case 48:
                    return new P048_UnknownMessage();
                case 49:
                    return new P049_UnknownMessage();
                case 50:
                    return new P050_UnknownMessage();
                case 51:
                    return new P051_UnknownMessage();
                case 52:
                    return new P052_UnknownMessage();
                case 53:
                    return new P053_UnknownMessage();
                case 54:
                    return new P054_UnknownMessage();
                case 55:
                    return new P055_UnknownMessage();
                case 56:
                    return new P056_UnknownMessage();
                case 57:
                    return new P057_UnknownMessage();
                case 58:
                    return new P058_UnknownMessage();
                case 59:
                    return new P059_UnknownMessage();
                case 60:
                    return new P060_UnknownMessage();
                case 61:
                    return new P061_UnknownMessage();
                case 62:
                    return new P062_UnknownMessage();
                case 63:
                    return new P063_UnknownMessage();
                case 64:
                    return new P064_UnknownMessage();
                case 65:
                    return new P065_UnknownMessage();
                case 66:
                    return new P066_UnknownMessage();
                case 67:
                    return new P067_UnknownMessage();
                case 68:
                    return new P068_UnknownMessage();
                case 69:
                    return new P069_UnknownMessage();
                case 70:
                    return new P070_UnknownMessage();
                case 71:
                    return new P071_UnknownMessage();
                case 72:
                    return new P072_UnknownMessage();
                case 73:
                    return new P073_UnknownMessage();
                case 74:
                    return new P074_UnknownMessage();
                case 75:
                    return new P075_UnknownMessage();
                case 76:
                    return new P076_UnknownMessage();
                case 77:
                    return new P077_UnknownMessage();
                case 78:
                    return new P078_UnknownMessage();
                case 79:
                    return new P079_UnknownMessage();
                case 80:
                    return new P080_UnknownMessage();
                case 81:
                    return new P081_UnknownMessage();
                case 82:
                    return new P082_UnknownMessage();
                case 83:
                    return new P083_UnknownMessage();
                case 84:
                    return new P084_UnknownMessage();
                case 85:
                    return new P085_UnknownMessage();
                case 86:
                    return new P086_UnknownMessage();
                case 87:
                    return new P087_UnknownMessage();
                case 88:
                    return new P088_UnknownMessage();
                case 89:
                    return new P089_UnknownMessage();
                case 90:
                    return new P090_UnknownMessage();
                case 91:
                    return new P091_UnknownMessage();
                case 92:
                    return new P092_UnknownMessage();
                case 93:
                    return new P093_UnknownMessage();
                case 94:
                    return new P094_UnknownMessage();
                case 95:
                    return new P095_UnknownMessage();
                case 96:
                    return new P096_UnknownMessage();
                case 97:
                    return new P097_UnknownMessage();
                case 98:
                    return new P098_UnknownMessage();
                case 99:
                    return new P099_UnknownMessage();
                case 100:
                    return new P100_UnknownMessage();
                case 101:
                    return new P101_UnknownMessage();
                case 102:
                    return new P102_UnknownMessage();
                case 103:
                    return new P103_UnknownMessage();
                case 104:
                    return new P104_UnknownMessage();
                case 105:
                    return new P105_UnknownMessage();
                case 106:
                    return new P106_UnknownMessage();
                case 107:
                    return new P107_UnknownMessage();
                case 108:
                    return new P108_UnknownMessage();
                case 109:
                    return new P109_UnknownMessage();
                case 110:
                    return new P110_UnknownMessage();
                case 111:
                    return new P111_UnknownMessage();
                case 112:
                    return new P112_UnknownMessage();
                case 113:
                    return new P113_UnknownMessage();
                case 114:
                    return new P114_UnknownMessage();
                case 115:
                    return new P115_UnknownMessage();
                case 116:
                    return new P116_UnknownMessage();
                case 117:
                    return new P117_UnknownMessage();
                case 118:
                    return new P118_UnknownMessage();
                case 119:
                    return new P119_UnknownMessage();
                case 120:
                    return new P120_UnknownMessage();
                case 121:
                    return new P121_UnknownMessage();
                case 122:
                    return new P122_UnknownMessage();
                case 123:
                    return new P123_UnknownMessage();
                case 124:
                    return new P124_UnknownMessage();
                case 125:
                    return new P125_UnknownMessage();
                case 126:
                    return new P126_UnknownMessage();
                case 127:
                    return new P127_UnknownMessage();
                case 128:
                    return new P128_UnknownMessage();
                case 129:
                    return new P129_UnknownMessage();
                case 130:
                    return new P130_UnknownMessage();
                case 131:
                    return new P131_UnknownMessage();
                case 132:
                    return new P132_UnknownMessage();
                case 133:
                    return new P133_UnknownMessage();
                case 134:
                    return new P134_UnknownMessage();
                case 135:
                    return new P135_UnknownMessage();
                case 136:
                    return new P136_UnknownMessage();
                case 137:
                    return new P137_UnknownMessage();
                case 138:
                    return new P138_UnknownMessage();
                case 139:
                    return new P139_UnknownMessage();
                case 140:
                    return new P140_UnknownMessage();
                case 141:
                    return new P141_UnknownMessage();
                case 142:
                    return new P142_UnknownMessage();
                case 143:
                    return new P143_UnknownMessage();
                case 144:
                    return new P144_UnknownMessage();
                case 145:
                    return new P145_UnknownMessage();
                case 146:
                    return new P146_UnknownMessage();
                case 147:
                    return new P147_UnknownMessage();
                case 148:
                    return new P148_UnknownMessage();
                case 149:
                    return new P149_UnknownMessage();
                case 150:
                    return new P150_UnknownMessage();
                case 151:
                    return new P151_UnknownMessage();
                case 152:
                    return new P152_UnknownMessage();
                case 153:
                    return new P153_UnknownMessage();
                case 154:
                    return new P154_UnknownMessage();
                case 155:
                    return new P155_UnknownMessage();
                case 156:
                    return new P156_UnknownMessage();
                case 157:
                    return new P157_UnknownMessage();
                case 158:
                    return new P158_UnknownMessage();
                case 159:
                    return new P159_UnknownMessage();
                case 160:
                    return new P160_UnknownMessage();
                case 161:
                    return new P161_UnknownMessage();
                case 162:
                    return new P162_UnknownMessage();
                case 163:
                    return new P163_UnknownMessage();
                case 164:
                    return new P164_UnknownMessage();
                case 165:
                    return new P165_UnknownMessage();
                case 166:
                    return new P166_UnknownMessage();
                case 167:
                    return new P167_UnknownMessage();
                case 168:
                    return new P168_UnknownMessage();
                case 169:
                    return new P169_UnknownMessage();
                case 170:
                    return new P170_UnknownMessage();
                case 171:
                    return new P171_UnknownMessage();
                case 172:
                    return new P172_UnknownMessage();
                case 173:
                    return new P173_UnknownMessage();
                case 174:
                    return new P174_UnknownMessage();
                case 175:
                    return new P175_UnknownMessage();
                case 176:
                    return new P176_UnknownMessage();
                case 177:
                    return new P177_UnknownMessage();
                case 178:
                    return new P178_UnknownMessage();
                case 179:
                    return new P179_UnknownMessage();
                case 180:
                    return new P180_UnknownMessage();
                case 181:
                    return new P181_UnknownMessage();
                case 182:
                    return new P182_UnknownMessage();
                case 183:
                    return new P183_UnknownMessage();
                case 184:
                    return new P184_UnknownMessage();
                case 185:
                    return new P185_UnknownMessage();
                case 186:
                    return new P186_UnknownMessage();
                case 187:
                    return new P187_UnknownMessage();
                case 188:
                    return new P188_UnknownMessage();
                case 189:
                    return new P189_UnknownMessage();
                case 190:
                    return new P190_UnknownMessage();
                case 191:
                    return new P191_UnknownMessage();
                case 192:
                    return new P192_UnknownMessage();
                case 193:
                    return new P193_UnknownMessage();
                case 194:
                    return new P194_UnknownMessage();
                case 195:
                    return new P195_UnknownMessage();
                case 196:
                    return new P196_UnknownMessage();
                case 197:
                    return new P197_UnknownMessage();
                case 198:
                    return new P198_UnknownMessage();
                case 199:
                    return new P199_UnknownMessage();
                case 200:
                    return new P200_UnknownMessage();
                case 201:
                    return new P201_UnknownMessage();
                case 203:
                    return new P203_UnknownMessage();
                case 204:
                    return new P204_UnknownMessage();
                case 205:
                    return new P205_UnknownMessage();
                case 206:
                    return new P206_UnknownMessage();
                case 207:
                    return new P207_UnknownMessage();
                case 208:
                    return new P208_UnknownMessage();
                case 209:
                    return new P209_UnknownMessage();
                case 210:
                    return new P210_UnknownMessage();
                case 211:
                    return new P211_UnknownMessage();
                case 212:
                    return new P212_UnknownMessage();
                case 213:
                    return new P213_UnknownMessage();
                case 214:
                    return new P214_UnknownMessage();
                case 215:
                    return new P215_UnknownMessage();
                case 216:
                    return new P216_UnknownMessage();
                case 217:
                    return new P217_UnknownMessage();
                case 218:
                    return new P218_UnknownMessage();
                case 219:
                    return new P219_UnknownMessage();
                case 220:
                    return new P220_UnknownMessage();
                case 221:
                    return new P221_UnknownMessage();
                case 222:
                    return new P222_UnknownMessage();
                case 223:
                    return new P223_UnknownMessage();
                case 224:
                    return new P224_UnknownMessage();
                case 225:
                    return new P225_UnknownMessage();
                case 226:
                    return new P226_UnknownMessage();
                case 227:
                    return new P227_UnknownMessage();
                default:
                    throw new NotImplementedException();
            }
        }
    }
}
