/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.CtoS
{
    public class P219_UnknownMessage : GenericTriggerableMessage
    {
        public byte Unknown0;
        public UID Unknown1;
        public UID Unknown2;
        public string Unknown3;
        
        public override ushort Header
        {
            get
            {
                return 219;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            this.Unknown0 = deserializer.ReadByte();
            this.Unknown1 = deserializer.ReadUID();
            this.Unknown2 = deserializer.ReadUID();
            this.Unknown3 = deserializer.ReadUtf16String();
        }
    }
}
