/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.CtoS
{
    public class P021_UnknownMessage : GenericTriggerableMessage
    {
        public short Unknown0;
        public short Unknown1;
        public byte Unknown2;
        public short Unknown3;
        public byte Unknown4;
        
        public override ushort Header
        {
            get
            {
                return 21;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            this.Unknown0 = deserializer.ReadInt16();
            this.Unknown1 = deserializer.ReadInt16();
            this.Unknown2 = deserializer.ReadByte();
            this.Unknown3 = deserializer.ReadInt16();
            this.Unknown4 = deserializer.ReadByte();
        }
    }
}
