/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.LoginServer.CtoS
{
    public class P02_ComputerUserNameMessage : GenericTriggerableMessage
    {
        public string UserName;
        public string ComputerName;
        
        public override ushort Header
        {
            get
            {
                return 2;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            this.UserName = deserializer.ReadUtf16String();
            this.ComputerName = deserializer.ReadUtf16String();
        }
    }
}
