/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.LoginServer.CtoS
{
    public class P04_UnknownMessage : GenericTriggerableMessage
    {
        public byte[] Unknown0;
        public UID Unknown1;
        
        public override ushort Header
        {
            get
            {
                return 4;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            byte unknown0Length = deserializer.ReadByte();
            if (unknown0Length > 97)
            {
                throw new InvalidDataException();
            }
            Unknown0 = new byte[unknown0Length];
            for (int i = 0; i < Unknown0.Length; i++)
            {
                Unknown0[i] = deserializer.ReadByte();
            }
            this.Unknown1 = deserializer.ReadUID();
        }
    }
}
