/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.LoginServer.CtoS
{
    public class P23_UnknownMessage : GenericTriggerableMessage
    {
        public int Unknown0;
        public string Unknown1;
        public byte[] Unknown2;
        
        public override ushort Header
        {
            get
            {
                return 23;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            this.Unknown0 = deserializer.ReadVarint();
            this.Unknown1 = deserializer.ReadUtf16String();
            byte unknown2Length = deserializer.ReadByte();
            if (unknown2Length > 255)
            {
                throw new InvalidDataException();
            }
            Unknown2 = new byte[unknown2Length];
            for (int i = 0; i < Unknown2.Length; i++)
            {
                Unknown2[i] = deserializer.ReadByte();
            }
        }
    }
}
