/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 21-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;

namespace GameRevision.GW2Emu.LoginServer.Messages.CtoS
{
    public class P04_UnknownMessage : IMessage
    {
        public byte[] Unknown0;
        public UID Unknown1;
        
        public ushort Header
        {
            get
            {
                return 4;
            }
        }
        
        public void Serialize(Serializer serializer) {}
        public void Deserialize(Deserializer deserializer)
        {
            byte unknown0Length = deserializer.ReadByte();
            if (unknown0Length > 97)
            {
                throw new InvalidDataException();
            }
            Unknown0 = new byte[unknown0Length];
            for (int i = 0; i < Unknown0.Length; i++)
            {
                Unknown0[i] = deserializer.ReadByte();
            }
            this.Unknown1 = deserializer.ReadUID();
        }
    }
}
