/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 22-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;
using GameRevision.GW2Emu.Common.Session;

namespace GameRevision.GW2Emu.LoginServer.Messages.CtoS
{
    public class P12_UnknownMessage : IMessage
    {
        public int Unknown0;
        public byte[] Unknown1;
        
        public ushort Header
        {
            get
            {
                return 12;
            }
        }
        
        public ISession Owner {  get;  set; }
        
        public void Serialize(Serializer serializer) {}
        public void Deserialize(Deserializer deserializer)
        {
            this.Unknown0 = deserializer.ReadVarint();
            ushort unknown1Length = deserializer.ReadUInt16();
            if (unknown1Length > 4098)
            {
                throw new InvalidDataException();
            }
            Unknown1 = new byte[unknown1Length];
            for (int i = 0; i < Unknown1.Length; i++)
            {
                Unknown1[i] = deserializer.ReadByte();
            }
        }
    }
}
