/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.LoginServer.CtoS
{
    public class P10_ClientSessionInfoMessage : GenericTriggerableMessage
    {
        public int Unknown0;
        public UID AccountId;
        public UID VerificationId;
        public string Unknown3;
        
        public override ushort Header
        {
            get
            {
                return 10;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            this.Unknown0 = deserializer.ReadVarint();
            this.AccountId = deserializer.ReadUID();
            this.VerificationId = deserializer.ReadUID();
            this.Unknown3 = deserializer.ReadUtf16String();
        }
    }
}
