/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.StoC
{
    public class P073_UnknownMessage : GenericMessage
    {
        public int Unknown0;
        public byte[] Unknown1;
        public byte Unknown2;
        public byte Unknown3;
        public byte Unknown4;
        
        public override ushort Header
        {
            get
            {
                return 73;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.WriteVarint(this.Unknown0);
            for (int i = 0; i < this.Unknown1.Length; i++)
            {
                serializer.Write(this.Unknown1[i]);
            }
            serializer.Write(this.Unknown2);
            serializer.Write(this.Unknown3);
            serializer.Write(this.Unknown4);
        }
    }
}
