/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.StoC
{
    public class P367_UnknownMessage : GenericMessage
    {
        public int Unknown0;
        public int Unknown1;
        public byte Unknown2;
        public UID Unknown3;
        public byte Unknown4;
        public int Unknown5;
        public byte Unknown6;
        public byte Unknown7;
        public int Unknown8;
        
        public override ushort Header
        {
            get
            {
                return 367;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.WriteVarint(this.Unknown0);
            serializer.WriteVarint(this.Unknown1);
            serializer.Write(this.Unknown2);
            serializer.WriteUID(this.Unknown3);
            serializer.Write(this.Unknown4);
            serializer.WriteVarint(this.Unknown5);
            serializer.Write(this.Unknown6);
            serializer.Write(this.Unknown7);
            serializer.WriteVarint(this.Unknown8);
        }
    }
}
