/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.StoC
{
    public class P377_UnknownMessage : GenericMessage
    {
        public UID Unknown0;
        public short Unknown1;
        public short Unknown2;
        public short[] Unknown3;
        public byte Unknown4;
        
        public override ushort Header
        {
            get
            {
                return 377;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.WriteUID(this.Unknown0);
            serializer.Write(this.Unknown1);
            serializer.Write(this.Unknown2);
            for (int i = 0; i < this.Unknown3.Length; i++)
            {
                serializer.Write(this.Unknown3[i]);
            }
            serializer.Write(this.Unknown4);
        }
    }
}
