/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.StoC
{
    public class P586_UnknownMessage : GenericMessage
    {
        public int[] Unknown0;
        
        public override ushort Header
        {
            get
            {
                return 586;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.Write((ushort)Unknown0.Length);
            for (int i = 0; i < Unknown0.Length; i++)
            {
                serializer.WriteVarint(Unknown0[i]);
            }
        }
    }
}
