/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.StoC
{
    public class P598_UnknownMessage : GenericMessage
    {
        public UID Unknown0;
        public UID Unknown1;
        public byte Unknown2;
        public UID[] Unknown3;
        public byte[] Unknown4;
        
        public override ushort Header
        {
            get
            {
                return 598;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.WriteUID(this.Unknown0);
            serializer.WriteUID(this.Unknown1);
            serializer.Write(this.Unknown2);
            serializer.Write((byte)Unknown3.Length);
            for (int i = 0; i < Unknown3.Length; i++)
            {
                serializer.WriteUID(Unknown3[i]);
            }
            serializer.Write((byte)Unknown4.Length);
            for (int i = 0; i < Unknown4.Length; i++)
            {
                serializer.Write(Unknown4[i]);
            }
        }
    }
}
