/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.StoC
{
    public class P635_UnknownMessage : GenericMessage
    {
        public short Unknown0;
        public short Unknown1;
        public short[] Unknown2;
        public byte[] Unknown3;
        
        public override ushort Header
        {
            get
            {
                return 635;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.Write(this.Unknown0);
            serializer.Write(this.Unknown1);
            serializer.Write((byte)Unknown2.Length);
            for (int i = 0; i < Unknown2.Length; i++)
            {
                serializer.Write(Unknown2[i]);
            }
            serializer.Write((byte)Unknown3.Length);
            for (int i = 0; i < Unknown3.Length; i++)
            {
                serializer.Write(Unknown3[i]);
            }
        }
    }
}
