//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Templates {
    
    private CommunicationDirection[] protocolField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Protocol", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CommunicationDirection[] Protocol {
        get {
            return this.protocolField;
        }
        set {
            this.protocolField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CommunicationDirection {
    
    private PacketType[] packetField;
    
    private ProtocolSimpleTypes typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Packet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PacketType[] Packet {
        get {
            return this.packetField;
        }
        set {
            this.packetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ProtocolSimpleTypes type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PacketType : UserNamedType {
    
    private BasicFieldType[] fieldField;
    
    private string headerField;
    
    private string typeSizeField;
    
    private string staticSizeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BasicFieldType[] Field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string typeSize {
        get {
            return this.typeSizeField;
        }
        set {
            this.typeSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string staticSize {
        get {
            return this.staticSizeField;
        }
        set {
            this.staticSizeField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(VarByteType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StructFieldType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StaticArrayFieldType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class BasicFieldType : UserNamedType {
    
    private PacketSimpleTypes typeField;
    
    private bool staticField;
    
    private bool staticFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PacketSimpleTypes type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool @static {
        get {
            return this.staticField;
        }
        set {
            this.staticField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool staticSpecified {
        get {
            return this.staticFieldSpecified;
        }
        set {
            this.staticFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
public enum PacketSimpleTypes {
    
    /// <remarks/>
    @byte,
    
    /// <remarks/>
    @short,
    
    /// <remarks/>
    @long,
    
    /// <remarks/>
    varint,
    
    /// <remarks/>
    @float,
    
    /// <remarks/>
    vec2,
    
    /// <remarks/>
    vec3,
    
    /// <remarks/>
    vec4,
    
    /// <remarks/>
    dw3,
    
    /// <remarks/>
    uid16,
    
    /// <remarks/>
    guid18,
    
    /// <remarks/>
    ascii,
    
    /// <remarks/>
    utf16,
    
    /// <remarks/>
    optional,
    
    /// <remarks/>
    array_static,
    
    /// <remarks/>
    array_var_small,
    
    /// <remarks/>
    array_var_big,
    
    /// <remarks/>
    buffer_static,
    
    /// <remarks/>
    buffer_var_small,
    
    /// <remarks/>
    buffer_var_big,
    
    /// <remarks/>
    varbyte,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicFieldType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(VarByteType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StructFieldType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StaticArrayFieldType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PacketType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UserNamedType {
    
    private MetaInfo infoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MetaInfo Info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MetaInfo {
    
    private string nameField;
    
    private string descriptionField;
    
    private string authorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class VarByteType : BasicFieldType {
    
    private string srcBytesField;
    
    private string destBytesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string srcBytes {
        get {
            return this.srcBytesField;
        }
        set {
            this.srcBytesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string destBytes {
        get {
            return this.destBytesField;
        }
        set {
            this.destBytesField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StaticArrayFieldType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class StructFieldType : BasicFieldType {
    
    private BasicFieldType[] fieldField;
    
    private string typeSizeField;
    
    private string staticSizeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BasicFieldType[] Field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string typeSize {
        get {
            return this.typeSizeField;
        }
        set {
            this.typeSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string staticSize {
        get {
            return this.staticSizeField;
        }
        set {
            this.staticSizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class StaticArrayFieldType : StructFieldType {
    
    private uint elementsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint elements {
        get {
            return this.elementsField;
        }
        set {
            this.elementsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
public enum ProtocolSimpleTypes {
    
    /// <remarks/>
    CtoLS,
    
    /// <remarks/>
    CtoGS,
    
    /// <remarks/>
    LStoC,
    
    /// <remarks/>
    GStoC,
}
