/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.StoC
{
    public class P327_UnknownMessage : GenericMessage
    {
        public Vector2 Unknown0;
        public Vector2 Unknown1;
        public Vector2 Unknown2;
        public Vector2 Unknown3;
        
        public override ushort Header
        {
            get
            {
                return 327;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.WriteVector2(this.Unknown0);
            serializer.WriteVector2(this.Unknown1);
            serializer.WriteVector2(this.Unknown2);
            serializer.WriteVector2(this.Unknown3);
        }
    }
}
