/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.StoC
{
    public class P697_UnknownMessage : GenericMessage
    {
        public UID Unknown0;
        public UID Unknown1;
        
        public override ushort Header
        {
            get
            {
                return 697;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.WriteUID(this.Unknown0);
            serializer.WriteUID(this.Unknown1);
        }
    }
}
