/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 24-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Session;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;

namespace GameRevision.GW2Emu.GameServer.Messages.CtoS
{
    public class P013_UnknownMessage : GenericMessage
    {
        public int Unknown0;
        public int Unknown1;
        public Vector3 Unknown2;
        public int Unknown3;
        public byte Unknown4;
        public byte Unknown5;
        
        public override ushort Header
        {
            get
            {
                return 13;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            this.Unknown0 = deserializer.ReadVarint();
            this.Unknown1 = deserializer.ReadVarint();
            this.Unknown2 = deserializer.ReadVector3();
            this.Unknown3 = deserializer.ReadVarint();
            this.Unknown4 = deserializer.ReadByte();
            this.Unknown5 = deserializer.ReadByte();
        }
    }
}
