/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 24-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Session;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;

namespace GameRevision.GW2Emu.GameServer.Messages.CtoS
{
    public class P030_UnknownMessage : GenericMessage
    {
        public int[] Unknown0;
        public int Unknown1;
        
        public override ushort Header
        {
            get
            {
                return 30;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            this.Unknown0 = new int[4];
            for (int i = 0; i < this.Unknown0.Length; i++)
            {
                this.Unknown0[i] = deserializer.ReadVarint();
            }
            this.Unknown1 = deserializer.ReadVarint();
        }
    }
}
