/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 24-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Session;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;

namespace GameRevision.GW2Emu.GameServer.Messages.CtoS
{
    public class P049_UnknownMessage : GenericMessage
    {
        public Vector2[] Unknown0;
        public int Unknown1;
        
        public override ushort Header
        {
            get
            {
                return 49;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            byte unknown0Length = deserializer.ReadByte();
            if (unknown0Length > 81)
            {
                throw new InvalidDataException();
            }
            Unknown0 = new Vector2[unknown0Length];
            for (int i = 0; i < Unknown0.Length; i++)
            {
                Unknown0[i] = deserializer.ReadVector2();
            }
            this.Unknown1 = deserializer.ReadVarint();
        }
    }
}
