/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.CtoS
{
    public class P050_UnknownMessage : GenericTriggerableMessage
    {
        public byte Unknown0;
        public Vector2[] Unknown1;
        public int Unknown2;
        
        public override ushort Header
        {
            get
            {
                return 50;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            this.Unknown0 = deserializer.ReadByte();
            byte unknown1Length = deserializer.ReadByte();
            if (unknown1Length > 255)
            {
                throw new InvalidDataException();
            }
            Unknown1 = new Vector2[unknown1Length];
            for (int i = 0; i < Unknown1.Length; i++)
            {
                Unknown1[i] = deserializer.ReadVector2();
            }
            this.Unknown2 = deserializer.ReadVarint();
        }
    }
}
