/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 22-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;
using GameRevision.GW2Emu.Common.Session;

namespace GameRevision.GW2Emu.GameServer.Messages.CtoS
{
    public class P089_UnknownMessage : IMessage
    {
        public int Unknown0;
        public int[] Unknown1;
        public UID Unknown2;
        public byte Unknown3;
        
        public ushort Header
        {
            get
            {
                return 89;
            }
        }
        
        public ISession Owner {  get;  set; }
        
        public void Serialize(Serializer serializer) {}
        public void Deserialize(Deserializer deserializer)
        {
            this.Unknown0 = deserializer.ReadVarint();
            byte unknown1Length = deserializer.ReadByte();
            if (unknown1Length > 161)
            {
                throw new InvalidDataException();
            }
            Unknown1 = new int[unknown1Length];
            for (int i = 0; i < Unknown1.Length; i++)
            {
                Unknown1[i] = deserializer.ReadVarint();
            }
            this.Unknown2 = deserializer.ReadUID();
            this.Unknown3 = deserializer.ReadByte();
        }
    }
}
