/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 24-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Session;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;

namespace GameRevision.GW2Emu.GameServer.Messages.CtoS
{
    public class P107_UnknownMessage : GenericMessage
    {
        public byte Unknown0;
        public short Unknown1;
        public int Unknown2;
        
        public override ushort Header
        {
            get
            {
                return 107;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            this.Unknown0 = deserializer.ReadByte();
            this.Unknown1 = deserializer.ReadInt16();
            this.Unknown2 = deserializer.ReadVarint();
        }
    }
}
