/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 22-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;
using GameRevision.GW2Emu.Common.Session;

namespace GameRevision.GW2Emu.GameServer.Messages.CtoS
{
    public class P147_UnknownMessage : IMessage
    {
        public string Unknown0;
        public byte[] Unknown1;
        public byte Unknown2;
        public byte Unknown3;
        public int Unknown4;
        public byte[] Unknown5;
        public int[] Unknown6;
        
        public ushort Header
        {
            get
            {
                return 147;
            }
        }
        
        public ISession Owner {  get;  set; }
        
        public void Serialize(Serializer serializer) {}
        public void Deserialize(Deserializer deserializer)
        {
            this.Unknown0 = deserializer.ReadUtf16String();
            this.Unknown1 = new byte[48];
            for (int i = 0; i < this.Unknown1.Length; i++)
            {
                this.Unknown1[i] = deserializer.ReadByte();
            }
            this.Unknown2 = deserializer.ReadByte();
            this.Unknown3 = deserializer.ReadByte();
            this.Unknown4 = deserializer.ReadVarint();
            byte unknown5Length = deserializer.ReadByte();
            if (unknown5Length > 33)
            {
                throw new InvalidDataException();
            }
            Unknown5 = new byte[unknown5Length];
            for (int i = 0; i < Unknown5.Length; i++)
            {
                Unknown5[i] = deserializer.ReadByte();
            }
            this.Unknown6 = new int[24];
            for (int i = 0; i < this.Unknown6.Length; i++)
            {
                this.Unknown6[i] = deserializer.ReadVarint();
            }
        }
    }
}
