/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.GameServer.CtoS
{
    public class P223_UnknownMessage : GenericTriggerableMessage
    {
        public int[] Unknown0;
        
        public override ushort Header
        {
            get
            {
                return 223;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            byte unknown0Length = deserializer.ReadByte();
            if (unknown0Length > 161)
            {
                throw new InvalidDataException();
            }
            Unknown0 = new int[unknown0Length];
            for (int i = 0; i < Unknown0.Length; i++)
            {
                Unknown0[i] = deserializer.ReadVarint();
            }
        }
    }
}
