/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.LoginServer.StoC
{
    public class P10_AccountMedalsMessage : GenericMessage
    {
        public int SyncCount;
        public byte[] MedalData;
        
        public override ushort Header
        {
            get
            {
                return 10;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.WriteVarint(this.SyncCount);
            serializer.Write((ushort)MedalData.Length);
            for (int i = 0; i < MedalData.Length; i++)
            {
                serializer.Write(MedalData[i]);
            }
        }
    }
}
