/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 08-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Core;
using GameRevision.GW2Emu.Core.Types;
using GameRevision.GW2Emu.Core.Serializers;

namespace GameRevision.GW2Emu.Messages.LoginServer.StoC
{
    public class P25_GameServerInfoMessage : GenericMessage
    {
        public int Location;
        public int Population;
        public int TransferCost;
        public int Unknown3;
        
        public override ushort Header
        {
            get
            {
                return 25;
            }
        }
        
        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            serializer.WriteVarint(this.Location);
            serializer.WriteVarint(this.Population);
            serializer.WriteVarint(this.TransferCost);
            serializer.WriteVarint(this.Unknown3);
        }
    }
}
